export const works = [
  // {
  //   id: 1,
  //   type: 'multiple',
  //   title: '作品集&简历[快速通道]',
  //   info: '其他-作品集',
  //   coverImg: 'http://img.chiyuu.cn/1.%E4%BD%9C%E5%93%81%E9%9B%86&%E7%AE%80%E5%8E%86.png',
  //   images: [
  //     'https://images.unsplash.com/photo-1564074621995-7c1f9a8ea9a2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80',
  //     'https://images.unsplash.com/photo-1564084571423-7894bb30fe80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  //     'https://images.unsplash.com/photo-1556911220-3bdc5f08618e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80'
  //   ]
  // },
  {
    id: 1,
    type: 'multiple',
    labelType: 'top',
    title: '2019作品集',
    info: '其他 - 作品集',
    coverImg: 'http://img.chiyuu.cn/2019%E4%BD%9C%E5%93%81%E9%9B%86%E5%B0%81%E9%9D%A2.png',
    images: [
      'http://img.chiyuu.cn/portfolio-1.png',
      'http://img.chiyuu.cn/portfolio-2.png',
      'http://img.chiyuu.cn/app-yiguan-1.png',
      'http://img.chiyuu.cn/app-yiguan-2.png',
      'http://img.chiyuu.cn/app-yiguan-3.png',
      'http://img.chiyuu.cn/app-yiguan-4.png',
      'http://img.chiyuu.cn/app-yiguan-5.png',
      'http://img.chiyuu.cn/app-yiguan-6.png',
      'http://img.chiyuu.cn/app-yiguan-7.png',
      'http://img.chiyuu.cn/app-yiguan-8.png',
      'http://img.chiyuu.cn/app-yiguan-9.png',
      'http://img.chiyuu.cn/app-yiguan-9-1.png',
      'http://img.chiyuu.cn/app-yiguan-9-2.png',
      'http://img.chiyuu.cn/app-yiguan-10.png',
      'http://img.chiyuu.cn/app-yiguan-10-a.gif',
      'http://img.chiyuu.cn/app-yiguan-10-b.png',
      'http://img.chiyuu.cn/app-yiguan-10-c.gif',
      'http://img.chiyuu.cn/app-yiguan-10-d.png',
      'http://img.chiyuu.cn/app-yiguan-10-1.gif',
      'http://img.chiyuu.cn/app-yiguan-10-2.png',
      'http://img.chiyuu.cn/app-yiguan-10-3.gif',
      'http://img.chiyuu.cn/app-yiguan-11.png',
      'http://img.chiyuu.cn/app-yiguan-11-1.png',
      'http://img.chiyuu.cn/app-yiguan-11-1-a.gif',
      'http://img.chiyuu.cn/app-yiguan-11-2.png',
      'http://img.chiyuu.cn/app-yiguan-12.png',
      'http://img.chiyuu.cn/web-kp-1.jpg',
      'http://img.chiyuu.cn/web-kp-2.jpg',
      'http://img.chiyuu.cn/web-kp-3.png',
      'http://img.chiyuu.cn/web-kp-4.jpg',
      'http://img.chiyuu.cn/web-kp-5.gif',
      'http://img.chiyuu.cn/web-kp-6.png',
      'http://img.chiyuu.cn/web-kp-7.png',
      'http://img.chiyuu.cn/web-kp-8.png',
      'http://img.chiyuu.cn/web-kp-9.gif',
      'http://img.chiyuu.cn/web-kp-10.jpg',
      'http://img.chiyuu.cn/web-kp-11.gif',
      'http://img.chiyuu.cn/web-kp-12.jpg',
      'http://img.chiyuu.cn/web-kp-13.gif',
      'http://img.chiyuu.cn/web-kp-14.jpg',
      'http://img.chiyuu.cn/web-kp-15.jpg',
      'http://img.chiyuu.cn/web-kp-16.gif',
      'http://img.chiyuu.cn/web-kp-17.jpg',
      'http://img.chiyuu.cn/web-kp-18.jpg',
      'http://img.chiyuu.cn/web-kp-19.png',
      'http://img.chiyuu.cn/web-anglee-1.png',
      'http://img.chiyuu.cn/web-anglee-2.jpg',
      'http://img.chiyuu.cn/web-anglee-3.jpg',
      'http://img.chiyuu.cn/web-anglee-4.jpg',
      'http://img.chiyuu.cn/web-anglee-5.jpg',
      'http://img.chiyuu.cn/web-anglee-6.jpg',
      'http://img.chiyuu.cn/web-anglee-7.jpg',
      'http://img.chiyuu.cn/web-anglee-8.jpg',
      'http://img.chiyuu.cn/web-anglee-9.jpg',
      'http://img.chiyuu.cn/web-anglee-10.jpg',
      'http://img.chiyuu.cn/web-anglee-11.jpg',
      'http://img.chiyuu.cn/web-anglee-12.jpg',
      'http://img.chiyuu.cn/portfolio-3.png',
      'http://img.chiyuu.cn/portfolio-jianbi-1.gif',
      'http://img.chiyuu.cn/portfolio-jianbi-2.gif',
      'http://img.chiyuu.cn/portfolio-chahua-1.png',
      'http://img.chiyuu.cn/portfolio-chahua-2.png',
      'http://img.chiyuu.cn/portfolio-chahua-3.png',
      'http://img.chiyuu.cn/portfolio-chahua-4.png',
      'http://img.chiyuu.cn/portfolio-chahua-5.png',
      'http://img.chiyuu.cn/portfolio-end.png',
    ]
  },
  {
    id: 2,
    type: 'multiple',
    title: '一罐APP「重设计」',
    info: 'app - redesign',
    coverImg: 'http://img.chiyuu.cn/2.%E4%B8%80%E7%BD%90app%28%E6%96%B0%29.png',
    images: [
      'http://img.chiyuu.cn/app-yiguan-1.png',
      'http://img.chiyuu.cn/app-yiguan-2.png',
      'http://img.chiyuu.cn/app-yiguan-3.png',
      'http://img.chiyuu.cn/app-yiguan-4.png',
      'http://img.chiyuu.cn/app-yiguan-5.png',
      'http://img.chiyuu.cn/app-yiguan-6.png',
      'http://img.chiyuu.cn/app-yiguan-7.png',
      'http://img.chiyuu.cn/app-yiguan-8.png',
      'http://img.chiyuu.cn/app-yiguan-9.png',
      'http://img.chiyuu.cn/app-yiguan-9-1.png',
      'http://img.chiyuu.cn/app-yiguan-9-2.png',
      'http://img.chiyuu.cn/app-yiguan-10.png',
      'http://img.chiyuu.cn/app-yiguan-10-a.gif',
      'http://img.chiyuu.cn/app-yiguan-10-b.png',
      'http://img.chiyuu.cn/app-yiguan-10-c.gif',
      'http://img.chiyuu.cn/app-yiguan-10-d.png',
      'http://img.chiyuu.cn/app-yiguan-10-1.gif',
      'http://img.chiyuu.cn/app-yiguan-10-2.png',
      'http://img.chiyuu.cn/app-yiguan-10-3.gif',
      'http://img.chiyuu.cn/app-yiguan-11.png',
      'http://img.chiyuu.cn/app-yiguan-11-1.png',
      'http://img.chiyuu.cn/app-yiguan-11-1-a.gif',
      'http://img.chiyuu.cn/app-yiguan-11-2.png',
      'http://img.chiyuu.cn/app-yiguan-12.png'
    ]
  },
  {
    id: '2-1',
    type: 'multiple',
    title: 'Paracraft新手试玩项目',
    info: 'UI - 客户端',
    coverImg: 'http://img.chiyuu.cn/paracaraf%E5%B0%81%E9%9D%A2.png',
    images: [
      'http://img.chiyuu.cn/web-kp-17.jpg',
      'http://img.chiyuu.cn/web-kp-18.jpg',
      'http://img.chiyuu.cn/web-kp-19.png'
    ]
  },
  {
    id: 3,
    type: 'multiple',
    title: 'Keepwork官网',
    info: 'Web - 官网设计',
    coverImg: 'http://img.chiyuu.cn/3.keepwork.png',
    images: [
      'http://img.chiyuu.cn/web-kp-1.jpg',
      'http://img.chiyuu.cn/web-kp-2.jpg',
      'http://img.chiyuu.cn/web-kp-3.png',
      'http://img.chiyuu.cn/web-kp-4.jpg',
      'http://img.chiyuu.cn/web-kp-5.gif',
      'http://img.chiyuu.cn/web-kp-6.png',
      'http://img.chiyuu.cn/web-kp-7.png',
      'http://img.chiyuu.cn/web-kp-8.png',
      'http://img.chiyuu.cn/web-kp-9.gif',
      'http://img.chiyuu.cn/web-kp-10.jpg',
      'http://img.chiyuu.cn/web-kp-11.gif',
      'http://img.chiyuu.cn/web-kp-12.jpg',
      'http://img.chiyuu.cn/web-kp-13.gif',
      'http://img.chiyuu.cn/web-kp-14.jpg',
      'http://img.chiyuu.cn/web-kp-15.jpg',
      'http://img.chiyuu.cn/web-kp-16.gif'
    ]
  },
  {
    id: 4,
    type: 'multiple',
    title: 'AngLee Film Studio',
    info: 'Web - 概念设计',
    coverImg: 'http://img.chiyuu.cn/4.anglee.png',
    images: [
      'http://img.chiyuu.cn/web-anglee-1.png',
      'http://img.chiyuu.cn/web-anglee-2.jpg',
      'http://img.chiyuu.cn/web-anglee-3.jpg',
      'http://img.chiyuu.cn/web-anglee-4.jpg',
      'http://img.chiyuu.cn/web-anglee-5.jpg',
      'http://img.chiyuu.cn/web-anglee-6.jpg',
      'http://img.chiyuu.cn/web-anglee-7.jpg',
      'http://img.chiyuu.cn/web-anglee-8.jpg',
      'http://img.chiyuu.cn/web-anglee-9.jpg',
      'http://img.chiyuu.cn/web-anglee-10.jpg',
      'http://img.chiyuu.cn/web-anglee-11.jpg',
      'http://img.chiyuu.cn/web-anglee-12.jpg',
    ]
  },
  {
    id: 5,
    type: 'multiple',
    title: 'Keepnote客户端',
    info: 'UI - 客户端',
    coverImg: 'http://img.chiyuu.cn/5.%E7%9F%A5%E8%AF%86%E5%BC%95%E6%93%8E.png',
    images: [
      'http://img.chiyuu.cn/client-keepnote-1.png',
      'http://img.chiyuu.cn/client-keepnote-2.png',
      'http://img.chiyuu.cn/client-keepnote-3.png',
    ]
  },
  {
    id: 6,
    type: 'multiple',
    title: '简笔画日记  [GIF]"',
    info: '插画 - 简笔画',
    coverImg: 'http://img.chiyuu.cn/6.%E7%AE%80%E7%AC%94%E7%94%BB%E6%97%A5%E8%AE%B0.png',
    images: [
      'http://img.chiyuu.cn/sticky-7.gif',
      'http://img.chiyuu.cn/sticky-6.gif',
      'http://img.chiyuu.cn/sticky-5.gif',
      'http://img.chiyuu.cn/sticky-4.gif',
      'http://img.chiyuu.cn/sticky-3.gif',
      'http://img.chiyuu.cn/sticky-2.gif',
      'http://img.chiyuu.cn/sticky-1.gif'
    ]
  },
  {
    id: 7,
    type: 'multiple',
    title: '手绘插画',
    info: '插画 - 手绘',
    coverImg: 'http://img.chiyuu.cn/7.%E6%89%8B%E7%BB%98%E6%8F%92%E7%94%BB.png',
    images: [
      'http://img.chiyuu.cn/Hp-1.png',
      'http://img.chiyuu.cn/Hp-2.png',
      'http://img.chiyuu.cn/Hp-3.png',
      'http://img.chiyuu.cn/Hp-4.png',
      'http://img.chiyuu.cn/Hp-5.png',
      'http://img.chiyuu.cn/Hp-6.png',
      'http://img.chiyuu.cn/Hp-7.png',
      'http://img.chiyuu.cn/Hp-8.png',
      'http://img.chiyuu.cn/Hp-9.png'
    ]
  },
  // {
  //   id: 8,
  //   type: 'multiple',
  //   title: '办会家品牌标识',
  //   info: '平面 - 品牌',
  //   coverImg: 'http://img.chiyuu.cn/8.%E5%8A%9E%E4%BC%9A%E5%AE%B6%E6%A0%87%E8%AF%86.png',
  //   images: [
  //     'https://images.unsplash.com/photo-1564074621995-7c1f9a8ea9a2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80',
  //     'https://images.unsplash.com/photo-1564084571423-7894bb30fe80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  //     'https://images.unsplash.com/photo-1556911220-3bdc5f08618e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80'
  //   ]
  // },
  {
    id: 8,
    type: 'multiple',
    title: '办会家品牌标识',
    info: '平面 - 品牌',
    coverImg: 'http://img.chiyuu.cn/%E5%8A%9E%E4%BC%9A%E5%AE%B6%E5%93%81%E7%89%8C%E6%A0%87%E8%AF%86%E5%B0%81%E9%9D%A2.png',
    images: [
      'http://img.chiyuu.cn/brand-banhuijia-1.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-2.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-3.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-4.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-5.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-6.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-7.jpg',
      'http://img.chiyuu.cn/brand-banhuijia-8.jpg',
    ]
  },
  {
    id: 9,
    type: 'multiple',
    title: '会·签到app',
    info: 'UI - 移动端app',
    coverImg: 'http://img.chiyuu.cn/9.%E4%BC%9A%E7%AD%BE%E5%88%B0app.png',
    images: [
      'http://img.chiyuu.cn/app-hqd-1.jpg',
      'http://img.chiyuu.cn/app-hqd-2.jpg',
      'http://img.chiyuu.cn/app-hqd-3.jpg',
    ]
  },
  {
    id: 11,
    type: 'multiple',
    title: '办会家品牌标识',
    info: '平面 - 品牌',
    coverImg: 'http://img.chiyuu.cn/%E7%BE%8E%E6%9C%AF%E9%A6%86%E5%B0%81%E9%9D%A2.png',
    images: [
      'http://img.chiyuu.cn/meishuguan-1.jpg',
      'http://img.chiyuu.cn/meishuguan-2.jpg',
      'http://img.chiyuu.cn/meishuguan-3.jpg',
      'http://img.chiyuu.cn/meishuguan-4.jpg',

    ]
  },
  // {
  //   id: 10,
  //   type: 'multiple',
  //   title: 'Like in space',
  //   info: '平面 - 耳机海报',
  //   coverImg: 'http://img.chiyuu.cn/10.like%20in%20space.png',
  //   images: [
  //     'https://images.unsplash.com/photo-1564074621995-7c1f9a8ea9a2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80',
  //     'https://images.unsplash.com/photo-1564084571423-7894bb30fe80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  //     'https://images.unsplash.com/photo-1556911220-3bdc5f08618e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80'
  //   ]
  // },
  // {
  //   id: 11,
  //   type: 'multiple',
  //   title: '汉阳区今日美术馆设计',
  //   info: '空间 - 建筑设计',
  //   coverImg: 'http://img.chiyuu.cn/11.%E6%B1%89%E9%98%B3%E5%8C%BA%E4%BB%8A%E6%97%A5%E7%BE%8E%E6%9C%AF%E9%A6%86%E8%AE%BE%E8%AE%A1-%E6%AF%95%E4%B8%9A%E8%AE%BE%E8%AE%A1.png',
  //   images: [
  //     'https://images.unsplash.com/photo-1564074621995-7c1f9a8ea9a2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80',
  //     'https://images.unsplash.com/photo-1564084571423-7894bb30fe80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  //     'https://images.unsplash.com/photo-1556911220-3bdc5f08618e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80'
  //   ]
  // }
]
export default works